In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("recom.csv")

In [4]:
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp
0  12.801685  0.012360                57         62        71        52
1  12.851654  0.004172                57         58        73        43
2  12.776773  0.000000                56         58        69        46
3  12.942001  0.031747                62         56        70        43
4  12.984652  0.000000                65         56        70        42

In [5]:
clay1=np.repeat('clay',1200)

In [6]:
clay1=clay1.reshape(1200,1)

In [7]:
clay1
type(clay1)

numpy.ndarray

In [8]:
sandy1=np.repeat('sandy',1300)
sandy1=sandy1.reshape(1300,1)
type(sandy1)

good1=np.repeat('good_bio_cond',1300)
good1=good1.reshape(1300,1)
type(good1)

numpy.ndarray

In [9]:
al1=np.repeat('alkaline',1300)
al1=al1.reshape(1300,1)

excellent=np.repeat('excellent_bio_cond',1100)
excellent=excellent.reshape(1100,1)
type(excellent)


numpy.ndarray

In [10]:
chalky1=np.repeat('chalky ',177)
chalky1=chalky1.reshape(177,1)

poor=np.repeat('poor_bio_cond',1577)
poor=poor.reshape(1577,1)
type(poor)

numpy.ndarray

In [11]:
soil1=np.concatenate((clay1,sandy1, al1, chalky1),axis=0)
bio_cond = np.concatenate((good1,excellent, poor),axis=0)

In [12]:
type(soil1)
type(bio_cond)

numpy.ndarray

In [13]:
soil1
type(soil1)

numpy.ndarray

In [14]:
from random import shuffle

In [15]:
print (soil1)

[['clay']
 ['clay']
 ['clay']
 ...
 ['chalky ']
 ['chalky ']
 ['chalky ']]


In [16]:
type(soil1)

numpy.ndarray

In [17]:
np.random.shuffle(soil1)
np.random.shuffle(bio_cond)

In [18]:
type(soil1)

numpy.ndarray

In [19]:
soil1

array([['sandy'],
       ['alkaline'],
       ['clay'],
       ...,
       ['sandy'],
       ['sandy'],
       ['alkaline']], dtype='<U8')

In [20]:
data['soil']=soil1

In [21]:
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776773  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  
0     sandy  
1  alkaline  
2      clay  
3     sandy  
4     sandy

In [22]:
df = pd.DataFrame(data)

In [23]:
one = pd.get_dummies(df['soil'])

In [24]:
one['alkaline']
df['alkaline']=one['alkaline']
df['sandy']=one['sandy']
df['chalky'] = one['chalky ']
df['clay']=one['clay']

In [25]:
df.drop(['soil'],axis=1)

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0     12.801685  0.012360                57         62        71        52   
1     12.851654  0.004172                57         58        73        43   
2     12.776773  0.000000                56         58        69        46   
3     12.942001  0.031747                62         56        70        43   
4     12.984652  0.000000                65         56        70        42   
...         ...       ...               ...        ...       ...       ...   
3972  12.959730  0.000000                30         72        85        58   
3973  12.985416  0.000000                30         70        87        52   
3974  12.947405  0.000300                33         70        86        53   
3975  12.771689  0.000000                35         69        85        53   
3976  12.845779  0.010131                36         70        86        53   

      alkaline  sandy  chalky  clay  
0            0      1       0     0  
1            1      0       0     0  
2            0      0       0     1  
3            0      1       0     0  
4            0      1       0     0  
...        ...    ...     ...   ...  
3972         0      1       0     0  
3973         1      0       0     0  
3974         0      1       0     0  
3975         0      1       0     0  
3976         1      0       0     0  

[3977 rows x 10 columns]

In [26]:
data['bio']=bio_cond

In [27]:
df = pd.DataFrame(data)

In [28]:
one = pd.get_dummies(df['bio'])

In [29]:
df

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0     12.801685  0.012360                57         62        71        52   
1     12.851654  0.004172                57         58        73        43   
2     12.776773  0.000000                56         58        69        46   
3     12.942001  0.031747                62         56        70        43   
4     12.984652  0.000000                65         56        70        42   
...         ...       ...               ...        ...       ...       ...   
3972  12.959730  0.000000                30         72        85        58   
3973  12.985416  0.000000                30         70        87        52   
3974  12.947405  0.000300                33         70        86        53   
3975  12.771689  0.000000                35         69        85        53   
3976  12.845779  0.010131                36         70        86        53   

          soil  alkaline  sandy  chalky  clay                 bio  
0        sandy         0      1       0     0       good_bio_cond  
1     alkaline         1      0       0     0       good_bio_cond  
2         clay         0      0       0     1  excellent_bio_cond  
3        sandy         0      1       0     0       poor_bio_cond  
4        sandy         0      1       0     0       good_bio_cond  
...        ...       ...    ...     ...   ...                 ...  
3972     sandy         0      1       0     0       poor_bio_cond  
3973  alkaline         1      0       0     0       good_bio_cond  
3974     sandy         0      1       0     0       poor_bio_cond  
3975     sandy         0      1       0     0       good_bio_cond  
3976  alkaline         1      0       0     0  excellent_bio_cond  

[3977 rows x 12 columns]

In [30]:
one

excellent_bio_cond  good_bio_cond  poor_bio_cond
0                      0              1              0
1                      0              1              0
2                      1              0              0
3                      0              0              1
4                      0              1              0
...                  ...            ...            ...
3972                   0              0              1
3973                   0              1              0
3974                   0              0              1
3975                   0              1              0
3976                   1              0              0

[3977 rows x 3 columns]

In [31]:
df['excellent_bio_cond']=one['excellent_bio_cond']
df['poor_bio_cond']=one['poor_bio_cond']
df['good_bio_cond'] = one['good_bio_cond']

In [32]:
data['excellent']=df['excellent_bio_cond']
data['poor']=df['poor_bio_cond']
data['good']=df['good_bio_cond']

In [33]:
data

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0     12.801685  0.012360                57         62        71        52   
1     12.851654  0.004172                57         58        73        43   
2     12.776773  0.000000                56         58        69        46   
3     12.942001  0.031747                62         56        70        43   
4     12.984652  0.000000                65         56        70        42   
...         ...       ...               ...        ...       ...       ...   
3972  12.959730  0.000000                30         72        85        58   
3973  12.985416  0.000000                30         70        87        52   
3974  12.947405  0.000300                33         70        86        53   
3975  12.771689  0.000000                35         69        85        53   
3976  12.845779  0.010131                36         70        86        53   

          soil  alkaline  sandy  chalky  clay                 bio  \
0        sandy         0      1       0     0       good_bio_cond   
1     alkaline         1      0       0     0       good_bio_cond   
2         clay         0      0       0     1  excellent_bio_cond   
3        sandy         0      1       0     0       poor_bio_cond   
4        sandy         0      1       0     0       good_bio_cond   
...        ...       ...    ...     ...   ...                 ...   
3972     sandy         0      1       0     0       poor_bio_cond   
3973  alkaline         1      0       0     0       good_bio_cond   
3974     sandy         0      1       0     0       poor_bio_cond   
3975     sandy         0      1       0     0       good_bio_cond   
3976  alkaline         1      0       0     0  excellent_bio_cond   

      excellent_bio_cond  poor_bio_cond  good_bio_cond  excellent  poor  good  
0                      0              0              1          0     0     1  
1                      0              0              1          0     0     1  
2                      1              0              0          1     0     0  
3                      0              1              0          0     1     0  
4                      0              0              1          0     0     1  
...                  ...            ...            ...        ...   ...   ...  
3972                   0              1              0          0     1     0  
3973                   0              0              1          0     0     1  
3974                   0              1              0          0     1     0  
3975                   0              0              1          0     0     1  
3976                   1              0              0          1     0     0  

[3977 rows x 18 columns]

In [34]:
data.drop(['bio','soil'],axis=1)
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776773  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  alkaline  sandy  chalky  clay                 bio  \
0     sandy         0      1       0     0       good_bio_cond   
1  alkaline         1      0       0     0       good_bio_cond   
2      clay         0      0       0     1  excellent_bio_cond   
3     sandy         0      1       0     0       poor_bio_cond   
4     sandy         0      1       0     0       good_bio_cond   

   excellent_bio_cond  poor_bio_cond  good_bio_cond  excellent  poor  good  
0                   0              0              1          0     0     1  
1                   0              0              1          0     0     1  
2                   1              0              0          1     0     0  
3                   0              1              0          0     1     0  
4                   0              0              1          0     0     1

In [35]:
# for row in df.iterrows():
#     print row

In [36]:
data[0:1]

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685   0.01236                57         62        71        52   

    soil  alkaline  sandy  chalky  clay            bio  excellent_bio_cond  \
0  sandy         0      1       0     0  good_bio_cond                   0   

   poor_bio_cond  good_bio_cond  excellent  poor  good  
0              0              1          0     0     1

In [37]:
data[0:1]["Moisture"]

0    12.801685
Name: Moisture, dtype: float64

In [38]:
df2 = data.values
type(df2)

numpy.ndarray

In [39]:
df2[0,1]
    

0.0123605

In [40]:
df2.shape

(3977, 18)

In [41]:
data['yield'] = 0

In [42]:
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776773  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  alkaline  sandy  chalky  clay                 bio  \
0     sandy         0      1       0     0       good_bio_cond   
1  alkaline         1      0       0     0       good_bio_cond   
2      clay         0      0       0     1  excellent_bio_cond   
3     sandy         0      1       0     0       poor_bio_cond   
4     sandy         0      1       0     0       good_bio_cond   

   excellent_bio_cond  poor_bio_cond  good_bio_cond  excellent  poor  good  \
0                   0              0              1          0     0     1   
1                   0              0              1          0     0     1   
2                   1              0              0          1     0     0   
3                   0              1              0          0     1     0   
4                   0              0              1          0     0     1   

   yield  
0      0  
1      0  
2      0  
3      0  
4      0

In [43]:
a= 0
b = 0
c= 0
d = 0
arr = np.zeros((3977,1))


for i in range(3977):
    if(((df2[i, 0] < 12.8)  or (df2[i, 1] > 0.005)) and (df2[i, 2] <60) and (df2[i, 3] > 55) and ((df2[i, 10] == 1.0) or (df2[i, 8] == 1.0))):
        #print i
        b = b + 1
        arr[i,0] = 2
        
for i in range(3977):
    if(((df2[i, 0] < 12.8)  or (df2[i, 1] > 0.5)) and (df2[i, 2] <50) and (df2[i, 3] > 45) and ((df2[i, 10] == 1.0) or (df2[i, 9] == 1.0) or (df2[i, 8] == 1.0))):
        #print i
        c= c + 1
        arr[i,0] = 3
        
for i in range(3977):
    if(((df2[i, 0] < 12.8)  or (df2[i, 1] == 0.0)) and (df2[i, 2] <90) and (df2[i, 3] < 90) and ((df2[i, 10] == 1.0) or (df2[i, 9] == 1.0) or (df2[i, 7] == 1.0) or (df2[i, 8] == 1.0))):
        #print i
        d= d + 1
        arr[i,0] = 4
        
for i in range(3977):
    if(((df2[i, 0] > 12.6 and df2[i, 0] < 13.5)  or (df2[i, 1] > 0.000001)) and (df2[i, 2] > 40 and df2[i, 2] < 100) and (df2[i, 3] > 52 and df2[i, 3] < 100) and (df2[i, 10] == 1.0)  ):
        #print i
        a = a + 1
        arr[i,0] = 1
        


In [44]:
print (arr)
arr.reshape(3977,1)

[[2.]
 [0.]
 [1.]
 ...
 [0.]
 [4.]
 [0.]]


array([[2.],
       [0.],
       [1.],
       ...,
       [0.],
       [4.],
       [0.]])

In [45]:
data['final yield']=arr

In [46]:
data

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0     12.801685  0.012360                57         62        71        52   
1     12.851654  0.004172                57         58        73        43   
2     12.776773  0.000000                56         58        69        46   
3     12.942001  0.031747                62         56        70        43   
4     12.984652  0.000000                65         56        70        42   
...         ...       ...               ...        ...       ...       ...   
3972  12.959730  0.000000                30         72        85        58   
3973  12.985416  0.000000                30         70        87        52   
3974  12.947405  0.000300                33         70        86        53   
3975  12.771689  0.000000                35         69        85        53   
3976  12.845779  0.010131                36         70        86        53   

          soil  alkaline  sandy  chalky  clay                 bio  \
0        sandy         0      1       0     0       good_bio_cond   
1     alkaline         1      0       0     0       good_bio_cond   
2         clay         0      0       0     1  excellent_bio_cond   
3        sandy         0      1       0     0       poor_bio_cond   
4        sandy         0      1       0     0       good_bio_cond   
...        ...       ...    ...     ...   ...                 ...   
3972     sandy         0      1       0     0       poor_bio_cond   
3973  alkaline         1      0       0     0       good_bio_cond   
3974     sandy         0      1       0     0       poor_bio_cond   
3975     sandy         0      1       0     0       good_bio_cond   
3976  alkaline         1      0       0     0  excellent_bio_cond   

      excellent_bio_cond  poor_bio_cond  good_bio_cond  excellent  poor  good  \
0                      0              0              1          0     0     1   
1                      0              0              1          0     0     1   
2                      1              0              0          1     0     0   
3                      0              1              0          0     1     0   
4                      0              0              1          0     0     1   
...                  ...            ...            ...        ...   ...   ...   
3972                   0              1              0          0     1     0   
3973                   0              0              1          0     0     1   
3974                   0              1              0          0     1     0   
3975                   0              0              1          0     0     1   
3976                   1              0              0          1     0     0   

      yield  final yield  
0         0          2.0  
1         0          0.0  
2         0          1.0  
3         0          0.0  
4         0          4.0  
...     ...          ...  
3972      0          4.0  
3973      0          4.0  
3974      0          0.0  
3975      0          4.0  
3976      0          0.0  

[3977 rows x 20 columns]

In [47]:
data = data.drop(['excellent_bio_cond','poor_bio_cond','good_bio_cond'],axis=1)

In [48]:
data

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0     12.801685  0.012360                57         62        71        52   
1     12.851654  0.004172                57         58        73        43   
2     12.776773  0.000000                56         58        69        46   
3     12.942001  0.031747                62         56        70        43   
4     12.984652  0.000000                65         56        70        42   
...         ...       ...               ...        ...       ...       ...   
3972  12.959730  0.000000                30         72        85        58   
3973  12.985416  0.000000                30         70        87        52   
3974  12.947405  0.000300                33         70        86        53   
3975  12.771689  0.000000                35         69        85        53   
3976  12.845779  0.010131                36         70        86        53   

          soil  alkaline  sandy  chalky  clay                 bio  excellent  \
0        sandy         0      1       0     0       good_bio_cond          0   
1     alkaline         1      0       0     0       good_bio_cond          0   
2         clay         0      0       0     1  excellent_bio_cond          1   
3        sandy         0      1       0     0       poor_bio_cond          0   
4        sandy         0      1       0     0       good_bio_cond          0   
...        ...       ...    ...     ...   ...                 ...        ...   
3972     sandy         0      1       0     0       poor_bio_cond          0   
3973  alkaline         1      0       0     0       good_bio_cond          0   
3974     sandy         0      1       0     0       poor_bio_cond          0   
3975     sandy         0      1       0     0       good_bio_cond          0   
3976  alkaline         1      0       0     0  excellent_bio_cond          1   

      poor  good  yield  final yield  
0        0     1      0          2.0  
1        0     1      0          0.0  
2        0     0      0          1.0  
3        1     0      0          0.0  
4        0     1      0          4.0  
...    ...   ...    ...          ...  
3972     1     0      0          4.0  
3973     0     1      0          4.0  
3974     1     0      0          0.0  
3975     0     1      0          4.0  
3976     0     0      0          0.0  

[3977 rows x 17 columns]

In [49]:
data = data.drop(['soil','bio','excellent','poor','good','yield'],axis = 1)

In [50]:
a = np.unique(data['final yield'])
a

array([0., 1., 2., 3., 4.])

In [51]:
data.to_csv('finalyield.csv')

In [52]:
from sklearn.preprocessing import OneHotEncoder

In [53]:
dt = pd.read_csv('finalyield.csv')

In [54]:
X = dt.drop(['final yield'],axis=1)
Y = dt['final yield']
Y= Y.to_frame()
Y

final yield
0             2.0
1             0.0
2             1.0
3             0.0
4             4.0
...           ...
3972          4.0
3973          4.0
3974          0.0
3975          4.0
3976          0.0

[3977 rows x 1 columns]

In [55]:
Y = Y.values
type(Y)

numpy.ndarray

In [56]:
onehot_encoder = OneHotEncoder(sparse=False)
Y = Y.reshape(len(Y), 1)
onehot_encoded = onehot_encoder.fit_transform(Y)
print (onehot_encoded)

[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]


In [57]:
from sklearn.model_selection import train_test_split


In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=0.3)

In [59]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [60]:
rf = RandomForestClassifier(n_estimators=140)
rf.fit(X_train,y_train)
yeild = rf.predict(X_test)
yeild

array([4., 4., 4., ..., 1., 4., 4.])

In [61]:
from sklearn.metrics import accuracy_score

In [62]:
acc = accuracy_score(y_test,yeild)
acc

0.9916247906197655

In [63]:
from matplotlib import pyplot as plt

In [64]:
test_vector = np.reshape(np.asarray([12.737998,0.026821,61,56,70,42,1.0,0.0,0.0,0.0,0.0]),(1,11))
p = int(rf.predict(test_vector)[0])
yield_list = ['20-30%','30-40%','50%','60-70%','80-100%']
print (yield_list[p])

80-100%
